# Generated by Django 2.0.5 on 2019-04-21 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='upc',
            field=models.CharField(max_length=50),
        ),
    ]
