# Generated by Django 2.0.5 on 2019-04-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20190421_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='upc',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
